import "./globals.css";
import NavigationBar from "../ui/Header/NavigationBar";
import Footer from "../ui/Footer/Footer";
import { Ubuntu } from "next/font/google";


const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ubuntu.variable}>
      <body className="font-ubuntu">
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
